### ISSUE TITLE
Question about writing to rpmb when rpmb space is full

### ISSUE THREAD

**Issue by jhcheon1000** [OP-TEE/optee_client#322]
Hi,
What happens internally in optee if the rpmb space is full before the write counter reaches max?
I couldn't find an error code related to this.

Do I have to manage data size list?

**Comment by jforissier** [comment]
Hi @jhcheon1000,

The RPMB filesystem uses `tee_mm_alloc()` and `tee_mm_alloc2()` to allocate space inside the partition. So when there is no space left, the error is detected by these functions. In this case the `struct tee_file_operations` function that triggers the error returns either `TEE_ERROR_STORAGE_NO_SPACE` (see `rpmb_fs_write_primitive()`), or `TEE_ERROR_OUT_OF_MEMORY`.

I suppose `TEE_ERROR_OUT_OF_MEMORY` is not a very good code for this condition and all occurrences should probably be converted to `TEE_ERROR_STORAGE_NO_SPACE`. But, in any case you do not need to track data size by yourself -- that would be impossible, especially since the file system stores metadata, too.
