### ISSUE TITLE
Standalone compilation issue : fatal error: uuid/uuid.h: No such file or directory

### ISSUE THREAD

**Issue by clementfaure** [OP-TEE/optee_client#329]
Hello!

I have some issues with the standalone compilation of `optee-client` since this patch 15605824fd823cdf257c88ed3c94e8381fe552a4
```
$ cd optee-client
$ CROSS_COMPILE=/toolchains/arm/bin/arm-linux-gnueabihf- \
PKG_CONFIG_PATH=/toolchains/arm/lib/pkgconfig/:$PKG_CONFIG_PATH \
make
....
Finding uuid.pc
pkg-config --atleast-version=2.34 uuid
Building libteeacl.so
  CC      src/group.c
In file included from src/group.c:6:
/home/bamboo/optee_client-3.19.0/libteeacl/include/teeacl.h:15:10: fatal error: uuid/uuid.h: No such file or directory
   15 | #include <uuid/uuid.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:41: /home/bamboo/optee_client-3.19.0/libteeacl/../out/libteeacl/group.o] Error 1
make: *** [Makefile:51: build-libteeacl] Error 2
```
I've manually added `libuuid` to the `toolchain`
```
$ pkg-config --cflags uuid
-I/toolchains/arm/include/uuid
```

Shouldn't it be `#include <uuid.h>` instead ?
https://github.com/OP-TEE/optee_client/blob/13123dea4bce6a52365b8d9c063a8e8b26ea9946/libteeacl/include/teeacl.h#L13-L16
@eaaltonen Am I missing something?

**Comment by eaaltonen** [comment]
@clementfaure : I agree it's more portable, and preferable to use #include <uuid.h>  there. I opened PR #330 to fix this. I presume that version works for you.

@igoropaniuk : unfortunately both work in native build, which may be why I missed the issue
```
$ pkg-config --cflags uuid
-I/usr/include/uuid
```

Since CMake version 3.6 it has been possible to [create IMPORTED_TARGET](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) from pkg-config files. The imported targets handle both include_directories and linking, and I believe they are in nearly every case the better option.

**Comment by clementfaure** [comment]
@eaaltonen Thanks for your help! Indeed, `#include <uuid.h>` works for me.
