### ISSUE TITLE
Implicit function declaration of reallocarray() 

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_client#339]
Buildroot reports build errors on `reallocarray()`, used in _libteeacl/src/group.c_:
http://autobuild.buildroot.net/results/9bda046c3af43765edbc27e2e3c9b6d4a635eef7
http://autobuild.buildroot.net/results/200fd19cfe909a5d05914451ced27423240e5353

For example, build log for the 1st above results:
```
/home/buildroot/autobuild/instance-2/output-1/build/optee-client-3.19.0/libteeacl/src/group.c:75:26: error: implicit declaration of function 'reallocarray' [-Werror=implicit-function-declaration]
   75 |                 groups = reallocarray(groups, grouplistsize, sizeof(gid_t));
      |                          ^~~~~~~~~~~~
/home/buildroot/autobuild/instance-2/output-1/build/optee-client-3.19.0/libteeacl/src/group.c:75:26: warning: nested extern declaration of 'reallocarray' [-Wnested-externs]
```

The issue is due to `reallocarray()` not being a standard function, as its man page says:
`reallocarray() is a nonstandard extension that first appeared in OpenBSD 5.6 and FreeBSD 11.0.`
The buildroot config that produce the failure is using GCC 11.3 (grep `BR2_GCC_VERSION` in the build [config](http://autobuild.buildroot.net/results/9bda046c3af43765edbc27e2e3c9b6d4a635eef7/config)). I could not find how to address that other that replacing `reallocarray()` with `realloc()` based implementation.

Any thoughs?

**Comment by eaaltonen** [comment]
I took a look at http://autobuild.buildroot.net/results/9bda046c3af43765edbc27e2e3c9b6d4a635eef7. The failure seems to be due to uClibc not implementing `reallocarray`. The appropriate reference here seems to be https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/tree/include/stdlib.h?h=v1.0.42&id=d46709504efa46e5b9b52739a48ab61b39fd4971

and the absence of any hits for `git grep reallocarray`. I opened PR#343 with two alternatives for fixes.
