### ISSUE TITLE
tee-supplicant readiness from systemd

### ISSUE THREAD

**Issue by embetrix** [OP-TEE/optee_client#382]
I use tee-supplicant to start from systemd unit as follow:

```
[Unit]
Description=TEE Supplicant
Before=myapps.target
DefaultDependencies=no

[Service]
ExecStart=/usr/sbin/tee-supplicant

[Install]
WantedBy=basic.target
```

systemd considers the unit as ready as soon as tee-supplicant starts, which causes problem of the applications  belonging to **myapps.target** as tee-supplicant sometimes is not ready yet and doesn't have access to the optee-storage.

I would like to change the unit to **Type=notify** as follow:

```
[Unit]
Description=TEE Supplicant
Before=myapps.target
DefaultDependencies=no

[Service]
Type=notify
ExecStart=/usr/sbin/tee-supplicant

[Install]
WantedBy=basic.target
```
But to signal readiness to systemd I have to send **sd_notify(0, "READY=1")** call.

what will be the best place in tee-supplicant code to place the call ?  ( I use only PKCS11 TA)

**ExecStart=/usr/sbin/tee-supplicant -d**  does't work here as it will be forking and cannot be used with Type=notify

**Comment by jforissier** [comment]
> systemd considers the unit as ready as soon as tee-supplicant starts, which causes problem of the applications  belonging to **myapps.target** as tee-supplicant sometimes is not ready yet and doesn't have access to the optee-storage.

OP-TEE is supposed to be able to wait for tee-supplicant to be ready, at least when it requests a TA to be loaded. I verified this in the QEMU environment (start the environment, kill `tee-supplicant`, run `xtest`: it waits, hit Ctr-C, run `/usr/bin/tee-supplicant -d`, run `xtest` again: it works). What kind of error do you get?

**Comment by jforissier** [comment]
CC @mcfrisk

**Comment by embetrix** [comment]
> > systemd considers the unit as ready as soon as tee-supplicant starts, which causes problem of the applications  belonging to **myapps.target** as tee-supplicant sometimes is not ready yet and doesn't have access to the optee-storage.
> 
> OP-TEE is supposed to be able to wait for tee-supplicant to be ready, at least when it requests a TA to be loaded. I verified this in the QEMU environment (start the environment, kill `tee-supplicant`, run `xtest`: it waits, hit Ctr-C, run `/usr/bin/tee-supplicant -d`, run `xtest` again: it works). What kind of error do you get?

But the applications that uses Optee-Storage (using pkcs11 calls) will for example not find the secure keys

**Comment by mikkorapeli-linaro** [comment]
Adding an sd_notify call to tell systemd when tee-supplicant is fully operational is a good idea. There is a similar issue when loading the ftpm kernel module for ftpm TA which needs to wait a bit after tee-supplicant startup. The issue could also be in optee and TAs, not directly tee-supplicant. Without systemd, with sysvinit, there is no real way to handle this. Either tee-supplicant interfaces or applications using them need to handle retries and failures caused by pending initialization.

**Comment by jforissier** [comment]
> But to signal readiness to systemd I have to send **sd_notify(0, "READY=1")** call.
> 
> what will be the best place in tee-supplicant code to place the call ? ( I use only PKCS11 TA)

That would be after the process has opened the TEE device, i.e., here: https://github.com/OP-TEE/optee_client/blob/4.2.0/tee-supplicant/src/tee_supplicant.c#L925

**Comment by mikkorapeli-linaro** [comment]
On a related not, I think the tee-supplicant udev rules and systemd service files should be submitted upsteam so that we can all share them. There are various issues for example in the meta-arm implementation in https://git.yoctoproject.org/meta-arm/tree/meta-arm/recipes-security/optee/optee-client
I'll try to get my setup working and then submit the changes. If anyone beats me to that, then great :)

**Comment by mikkorapeli-linaro** [comment]
@jforissier Are all the early TAs initialized at that point?

I think we had this relatively ugly workaround in https://gitlab.com/Linaro/trustedsubstrate/meta-ledge-secure/-/blob/main/meta-ledge-secure/recipes-security/optee/optee-client_%25.bbappend?ref_type=heads#L14
which does:

```
ExecStartPost=-/bin/sh -c "while [ ! $(pgrep tee-supplicant) ]; do sleep 0.1; done; /sbin/modprobe tpm_ftpm_tee"
```

so would be nice to get rid of that. Even better if the root cause for that issue is fixed since a long time in kernel and/or optee.

**Comment by jforissier** [comment]
> @jforissier Are all the early TAs initialized at that point?

Yes, early TAs are available immediately, they are self-contained in the TEE binary so there is no dependency as far as initialization goes. As soon as Normal World is able to invoke OP-TEE, it can execute an early TA. Of course when an early TA is first invoked it may need to use the supplicant services (secure storage etc.).

**Comment by embetrix** [comment]
@jforissier  @mikkorapeli-linaro  thanks for the insights :-) 

Just as notice, tee-supplicant could be used in initramfs as well, in this case it shouldn't pull libsystemd dependeny.

Maybe have an #ifdef SYSTEMD and generate two kind of tee-supplicant ?

**Comment by jforissier** [comment]
> Maybe have an #ifdef SYSTEMD and generate two kind of tee-supplicant ?

Oops, I don't like this idea :wink: We are trying to get rid of tee-supplicant (although it may not be possible in all cases, for example for platforms using custom plugins). So I'd rather not they become twins :laughing: 
Could `dlopen()` be an option?

**Comment by embetrix** [comment]
dlopen would be great :-)

**Comment by mikkorapeli-linaro** [comment]
Initramfs can use systemd. In fact, that has a lot of advantages for high level services and features like using TPM for secure storage and file system encryption. tee-supplicant has some issues running inside initramfs. Or maybe those are ftpm TA related. One of them is that all userspace services started inside initramfs need to be stopped before reboot to real target rootfs happens. Thus all storage used inside initramfs userspace will be lost when enterting real target rootfs. Kernel modules and related configuration in kernel can remain though. Except for ftpm for which the kernel modules need to be unloaded and re-loaded once real target rootfs has started tee-supplicant again. Hopefully it's just ftpm TA...

At optee-client/tee-supplicant build time, availability of systemd libs and headers should be checked, possibly with manual override for configuring. And if found, the sd_notify code path should be enabled and udev rules and service files installed to correct target locations. For example in yocto world, systemd support is a distro level feature and that can pull in systemd to dependency of optee-client recipe compilation. But this needs to be optional.

**Comment by mikkorapeli-linaro** [comment]
Using dlopen() is a good idea at runtime to avoid hard dependency to systemd libraries.

**Comment by embetrix** [comment]
for tee-supplicant systemd unit I added:

`ExecStartPre=/bin/udevadm trigger --action="add" --settle --subsystem-match="tee"`

**Comment by mikkorapeli-linaro** [comment]
Linaro Trusted Substrate Arm System Ready UEFI firmware (u-boot, optee and optee, for secure boot with TPM) and Trusted Reference Stack kernel and rootfs use this tee-supplicant udev rule currently:
https://gitlab.com/Linaro/trustedsubstrate/meta-ledge-secure/-/blob/main/meta-ledge-secure/recipes-security/optee/optee-client/optee-udev.rules?ref_type=heads

I'm trying to get the service file written correctly so that it can be started in initramfs and main rootfs correctly for systemd's tpm2.target (ftpm TA usecase). Lennart helped on systemd-devel: https://lists.freedesktop.org/archives/systemd-devel/2024-May/050283.html

**Comment by mikkorapeli-linaro** [comment]
And all these relate to the kernel RPMB support patches from Jens:

https://lore.kernel.org/linux-mmc/20240527121340.3931987-1-jens.wiklander@linaro.org/T/

which can remove tee-supplicant dependency from some RPMB related usecases. Unfortunately fTPM TA still needs the RPC setup done by tee-supplicant currently, and fTPM TA needs to enumerate at correct state which may be after tee-supplicant startup if meta-arm/yocto is used, see

https://git.yoctoproject.org/meta-arm/tree/meta-arm/recipes-security/optee-ftpm/optee-ftpm/0001-add-enum-to-ta-flags.patch

**Comment by jforissier** [comment]
It looks like we're making some good progress on fixing those perky dependency issues. @embetrix if you feel like submitting a patch for the `sd_notify()` support (with `dlopen()`), please do so. Thanks.

**Comment by mikkorapeli-linaro** [comment]
https://github.com/OP-TEE/optee_client/pull/383 is adding the startup indicator READY=1 but is there some mainloop location where we could also add a watchdog ping to systemd? Then we could set a watchdog with some high timer value in systemd service file and detect if tee-supplicant hangs. https://man7.org/linux/man-pages/man3/sd_notify.3.html

**Comment by embetrix** [comment]
@mikkorapeli-linaro IMHO watchdog notification is application specific, in my case I use only PKCS#TA, the scure Storage keys once read will be cached, even if tee-supplicant is not running or crashed.
I doubt that if a TA has some problems, restarting tee-supplicant would help ?

**Comment by embetrix** [comment]
solved by https://github.com/OP-TEE/optee_client/pull/383
